language: python

dist: xenial

python: "3.6"

install:
  - pip install -r requirements.test.txt

script:
  - pytest -p no:warnings

after_script:
  - coverage pytest -p no:warnings
  - coverage report -m